- name: "Ensure an old job is no longer present."
  ansible.builtin.cron:
    name: "delete-old-pings"
    state: absent
  ignore_errors: true
  become_user: "{{ app_user }}"
  become: yes
  tags: ["cron", "rails-cron"]

# 8 UTC is 3 EST
- name: Delete Old Pings
  ansible.builtin.cron:
    name: "delete-old-pings"
    minute: "4"
    hour: "8"
    job: '/bin/bash -lc "cd lrt/current && OTEL_SERVICE_NAME={{ app_name}}-cron bin/rails pings:prune"  2>&1 | logger -t [rails-cron]'
  ignore_errors: true
  become_user: "{{ app_user }}"
  become: yes
  tags: ["cron", "rails-cron"]

- name: "remove disable-expired-trial-accounts"
  ansible.builtin.cron:
    name: "disable-expired-trial-accounts"
    state: absent
  ignore_errors: true
  become_user: "{{ app_user }}"
  become: yes
  tags: ["cron", "rails-cron"]

# 9 UTC is 4 EST
- name: "add disable-expired-trial-accounts"
  ansible.builtin.cron:
    name: "delete-old-pings"
    minute: "4"
    hour: "9"
    job: '/bin/bash -lc "cd lrt/current && OTEL_SERVICE_NAME={{ app_name}}-trial bin/rails concierge:downgrade"  2>&1 | logger -t [rails-cron]'
  ignore_errors: true
  become_user: "{{ app_user }}"
  become: yes
  tags: ["cron", "rails-cron"]
