- name: Add app nginx-site config
  template:
    src: site.j2
    dest: "/etc/nginx/sites-available/{{ app_name }}"
    owner: www-data
    group: www-data
    mode: 0644
  ignore_errors: true
  tags: ["nginx", "nginx-site-config"]

- name: enable app site
  file:
    src: "/etc/nginx/sites-available/{{ app_name }}"
    dest: "/etc/nginx/sites-enabled/{{ app_name }}"
    owner: www-data
    group: www-data
    state: link
  ignore_errors: true
  tags: ["nginx", "nginx-site-config"]

- name: restart nginx
  service:
    name: nginx
    state: restarted
  ignore_errors: true
  tags: ["nginx", "nginx-site-config"]
