- name: install s3cmd
  apt:
    pkg: [ 's3cmd' ]
    state: present

- name: generate s3cmd config for backups
  template:
    src: s3cfg.j2
    dest: "/home/{{ app_user }}/.s3cfg"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0600
  tags: ['s3cmd']

- name: create directory for db back-up script
  ansible.builtin.file:
    path: "/home/{{ app_user }}/utils"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: generate the backup script
  template:
    src: backup.sh.j2
    dest: "/home/{{ app_user }}/utils/backup.sh"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0700
  tags: ['postgresql']

- name: schedule database backups
  ansible.builtin.cron:
    name: "application database backups"
    minute: "15"
    hour: "3,18"
    job: "bash -lc \"/home/{{ app_user }}/utils/backup.sh\" > /dev/null"
  become_user: "{{ app_user }}"
