- name: Install fail2ban
  apt:
    state: latest
    name: [fail2ban]
  tags: ['fail2ban']

- name: exclude developer's ip
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0600
  become: true
  tags: ['fail2ban', 'fail2ban-config']

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
  become: true
  tags: ['fail2ban', 'fail2ban-config']
