- name: tools that aren't necessarily needed.
  hosts: appservers
  become: yes
  roles:
    - { role: slack-notification, tags: ["slack-notification"] }
    - {
        role: database-backups,
        tags: ["backups", "db-backups", "database-backups"],
      }
