- name: configure redis
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: 0644
  tags: ['redis-config']

- name: restart redis
  ansible.builtin.systemd:
    name: redis-server
    enabled: yes
    state: restarted
  tags: ['redis-config']

